### ISSUE TITLE
Проблемы с деревом

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#32]
https://github.com/DmitryTell/Observer/assets/127039439/99792529-05cb-4db5-b2b6-c005b6eaa41f
Приоритет: High
Серьезность: Critical
Шаги 
1 впроекте создать файл mail_2
2 впроекте создать файл mail_8
3 впроекте создать файл mail_6

ОР файлы отобразились в порядке 

mail_2
mail_6
mail_8

ФР Файлы скачут и исчезают

Еще баг 
Шаг 
1. Удалить созданные файлы

ОР Файлы удалятся из дерева и не будут отображаться
ФР Появились файлы которые не отображались при создании

**Comment by nikolaykosasha** [comment]
Исправлен

**Comment by kushedow** [comment]
Перепроверить после рефакторинга

**Comment by kushedow** [comment]
Почему еще открыто? :)

**Comment by nikolaykosasha** [comment]
Исправлено
