### ISSUE TITLE
[BUG] Получение статусов от не выбранного ученика

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#51]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Описание

При трансляции кода(sharing/code_send) учеником 159, учитель получает статусы заданий(steps/status/to_mentor) от ученика 160 в окно сообщений

### Серьезность

Значительная ошибка, S3

### Приоритет

Medium

### Фактический результат

Статус заданий отображается в окне сообшений активного ученика

### Ожидаемый результат

Статус заданий отображается при активации отправителя сообщений

### Шаги для воспроизведения

1. Создать комнату
2. Присоединиться 2 учениками
3. Начать трансляцию у 2 ученика
4. Отправить статус задания от 1 ученика

### Окружение

```markdown
Версия Плагина: Observer App-1.2.8-test
Версия Браузера: 120.0.6099.234 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

https://github.com/DmitryTell/Observer/assets/127039439/16e6d8d9-9940-4418-ba8e-ddcbe2db114a

**Comment by nikolaykosasha** [comment]
03.12.2024 Дефект еще присутствует

**Comment by nikolaykosasha** [comment]
#bug #major #medium
@DmitryTell @NickMad17

**Comment by DmitryTell** [comment]
Должен быть исправлен после рефакторинга, проверь.

**Comment by nikolaykosasha** [comment]
Дефект не исправлен

https://github.com/DmitryTell/Observer/assets/127039439/4883387e-c131-40ad-9299-06d867e3904a

**Comment by nikolaykosasha** [comment]
@DmitryTell Обнови статус дефекта

**Comment by DmitryTell** [comment]
Исправил

**Comment by nikolaykosasha** [comment]
Исправлен. Закрываю.
