### ISSUE TITLE
Сброс набранного текста в поле "редактировании заданий" при отправке статуса учеником

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#52]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Описание

Когда учитель печатает текст в окне редактирования заданий и если в этот момент ученик отправит статус (steps/status/to_mentor) то  напечатанный  текст сбросится в окне. Так же и с чатами 

### Серьезность

Критическая ошибка, S2

### Приоритет

High

### Фактический результат

Текст сбрасывается. Необходиммо заново вводить текст

### Ожидаемый результат

Текст не сбрассывается. 

### Шаги для воспроизведения

1. Создать комнату
2. Подключить ученика
3. Нажать кнопку "Задание"
4. Ввести текст в поле задания
5. В плагине нажать кнопку "Help"

### Окружение

```markdown
- Версия Плагина: Observer App-1.2.8-test
- Версия Браузера: 120.0.6099.234 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

https://github.com/DmitryTell/Observer/assets/127039439/3924b724-69cd-42c3-a012-c282e3c764b8

**Comment by kushedow** [comment]
Перепроверить после рефакторинга

**Comment by nikolaykosasha** [comment]
Исправлено
