### ISSUE TITLE
Элемент "Нет соединения" отображается на странице после автоматического подключения к WebSocket

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#53]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Серьезность

Минорная ошибка, S4

### Приоритет

Medium

### Фактический результат

Элемент "Нет соединения" отображается на странице после автоматического подключения к WebSocket

### Ожидаемый результат

Элемент "Нет соединения" не отображается на странице после автоматического подключения к WebSocket

### Шаги для воспроизведения

1. Создать комнату
2. По средствам devtools перейти в режим offline
3. По средствам devtools возобновить подключение

### Окружение

```markdown
- Версия Браузера: 120.0.6099.234 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

[Rehost.log.txt](https://github.com/DmitryTell/Observer/files/14075711/Rehost.log.txt)

https://github.com/DmitryTell/Observer/assets/127039439/9c60adac-369f-49ee-95e4-19050a4908e5

**Comment by nikolaykosasha** [comment]
#bug #Minor #Medium

**Comment by DmitryTell** [comment]
Глеб сказал, оставить именно в таком виде

**Comment by nikolaykosasha** [comment]
Закрываю Issues
