### ISSUE TITLE
Отсутствует поле трансляции кода на странице учителя после того переименовали файл в проекте

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#55]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Описание

Во время трансляции кода если переименовать файл образуются дубликаты файла как в [Issues 54](https://github.com/DmitryTell/Observer/issues/54) последствия переименования файла приводят к тому что окно трансляции кода исчезает

### Серьезность

Критическая ошибка, S2

### Приоритет

High

### Фактический результат

Окно трансляции кода отсутствует. Отображается дублирующиеся файлы дерева проекта.

### Ожидаемый результат

В дереве проекта файл изменил название, трансляция продолжилась

### Шаги для воспроизведения

**Предусловия:** Создать комнату. Подключить ученика.
1.  Начать трансляцию кода ученика
2. В IDE переименовать файл в проекте

### Окружение

```markdown
- Версия плагина: Observer App-1.2.8-test
- Версия браузера: 120.0.6099.234 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

[Отсутствует окно кода.log](https://github.com/DmitryTell/Observer/files/14076407/default.log)
[Отсутствует окно кода.json](https://github.com/DmitryTell/Observer/files/14076422/default.json)
[Rec JS](https://transfiles.ru/iyenl) - Отпишитесь полезный ли это файл.

https://github.com/DmitryTell/Observer/assets/127039439/66b4a9e1-eec2-4ddf-9513-9c01e63145d4

**Comment by nikolaykosasha** [comment]
[+Файловое дерево.log](https://github.com/DmitryTell/Observer/files/14076446/%2B.log)

**Comment by kushedow** [comment]
Проверить после рефакторинга

**Comment by nikolaykosasha** [comment]
Исправлено
