### ISSUE TITLE
Отображается задание в новой комнате из закрытой комнаты

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#57]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Описание

В одной сессии создать комнату и отправить задания. Затем закрыть комнату и потом создать новую комнату, то в новой комнате будут отображаться задания из закрытой комнате.

### Серьезность

Значительная ошибка, S3

### Приоритет

Medium

### Фактический результат

Отображается задание в новой комнате из закрытой комнаты

### Ожидаемый результат

Новая комната пустая и не несет никакой истории предыдущих сессий.

### Шаги для воспроизведения

Предусловия: Открыть браузер, Создать комнату

1. Выбрать вкладку "Задание 1"
2. Ввести в поле задание, например "Задание 1 x-1"
3. Нажать кнопку "Отправить"
4. Выбрать вкладку "Задание 2"
5. Ввести в поле задание, например "Задание 2 x-2"
6. Нажать кнопку "Выйти"
7. Нажать кнопку "Создать комнату"

### Окружение

```markdown
- OS: MacOS 12.7.2 (21G1974)
- Версия браузера: 121.0.6167.85 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

https://github.com/DmitryTell/Observer/assets/127039439/20da500a-214e-4d8b-b540-96b3c84865f7

**Comment by nikolaykosasha** [comment]
Логи console [REC-D57.log](https://github.com/DmitryTell/Observer/files/14151373/REC-D57.log)

**Comment by kushedow** [comment]
при выходе из комнаты нужно ресетить store

**Comment by nikolaykosasha** [comment]
#bug #Major #Medium

**Comment by nikolaykosasha** [comment]
@kushedow Обнови статус дефекта

**Comment by nikolaykosasha** [comment]
@DmitryTell Обнови статус дефекта

**Comment by DmitryTell** [comment]
Исправил

**Comment by nikolaykosasha** [comment]
Исправлено. Закрываю.
