### ISSUE TITLE
Отсутствует поле трансляции кода на странице приложения после переключения трансляции

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#58]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Серьезность

Критическая ошибка, S2

### Приоритет

High

### Фактический результат

Новое поле трансляции кода не отрисовывается, отображается поле предыдущего юзера трансляции

### Ожидаемый результат

Поле трансляции отображает код подключенного к трансляции юзера

### Шаги для воспроизведения

Предусловия: Открыть браузер, Создать комнату, Подключить к комнате двух клиентов(юзеров)

1. Нажать на Юзера 1 (Клик по юзеру, начать трансляцию)
2. Выбрать файл из дерева проекта Юзера
3. Нажать на Юзера 2 (Клик по юзеру, начать трансляцию) 

### Окружение

```markdown
- OS: MacOS 12.7.2 (21G1974)
- Версия браузера: 121.0.6167.85 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

Логи console [REC-D58.log](https://github.com/DmitryTell/Observer/files/14151399/REC-D58.log)

https://github.com/DmitryTell/Observer/assets/127039439/e75a9034-93f5-4969-a645-48347d3af32d

**Comment by nikolaykosasha** [comment]
#bug #Critical #High

**Comment by DmitryTell** [comment]
Проверь, баг должен быть исправлен. Если нет, то необходимо созвониться и воспроизвести.

**Comment by nikolaykosasha** [comment]
Нужно созвониться. Повторился 1 раз. Потом исчез.

**Comment by nikolaykosasha** [comment]
https://github.com/DmitryTell/Observer/assets/127039439/bf7e786f-0bb4-4769-97d8-6705c28f205c

Надо очистку сделать после sharing_end

**Comment by nikolaykosasha** [comment]
@DmitryTell  Обнови статус, дефекта

**Comment by DmitryTell** [comment]
Исправлен

**Comment by nikolaykosasha** [comment]
Исправлено. Закрываю.
