### ISSUE TITLE
Поле трансляции кода изменяет свой размер при длинном коде в файле на странице хоста

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#59]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Описание

При трансляции кода если код в файле будет слишком длинным, поле трансляции изменяет свой размер и перекрывает дерево проекта. 

### Серьезность

Критическая ошибка, S2

### Приоритет

High

### Фактический результат

Поле трансляции кода перекрывает дерево проекта

### Ожидаемый результат

Поле трансляции кода имеет закрепленный размер и отображает транслируемый код

### Шаги для воспроизведения

**Предусловия:** Открыть браузер, Создать комнату, Подключить к комнате одного клиента(юзера), Подготовить проект с длинным кодом в файле в одну строку
1. Нажать на Юзера 1 (Клик по юзеру, начать трансляцию)
2. Выбрать файл подготовленный файл с длинным кодом в одну строку из дерева проекта Юзера

### Окружение

```markdown
- OS: MacOS 12.7.2 (21G1974)
- Версия браузера: 121.0.6167.85 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

[Log D-59.log](https://github.com/DmitryTell/Observer/files/14151430/Log.D-59.log)

https://github.com/DmitryTell/Observer/assets/127039439/601fb213-edca-43ff-a498-74ea76fb1426

**Comment by nikolaykosasha** [comment]
#bug #Critical #High

**Comment by DmitryTell** [comment]
Исправил

**Comment by nikolaykosasha** [comment]
Исправлено. Закрываю.
