### ISSUE TITLE
Нет отображения закрытия комнаты

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#6]
Шаги: 

1. Создать комнату
2. Ученик присоединился к комнате
3. Нажать кнопку выйти

Ожидаемый результат: Комната закрывается. Отображается экран создать комнату
Фактический результат: Событие "закрыть комнату" отправилось комната осталась открытой. 

https://github.com/DmitryTell/Observer/assets/127039439/fb052770-df95-43fc-adf6-cf58d9860a86

**Comment by kushedow** [comment]
Воспроизводится сейчас?

**Comment by nikolaykosasha** [comment]
@kushedow Нет. @DmitryTell Закрой Issues
