### ISSUE TITLE
Невидимое поле на странице хоста при начале трансляции

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#60]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Описание

При начале трансляции когда не выбран файл для трансляции неактивное(невидимое) поле трансляции кода ломает всю работу приложения. 

### Серьезность

Значительная ошибка, S3

### Приоритет

High

### Фактический результат

Неактивное поле трансляции кода перекрывает другие объекты страницы

### Ожидаемый результат

Неактивное поле трансляции кода имеет свой размер и не перекрывает другие объекты страницы

### Шаги для воспроизведения

Предусловия: Открыть браузер, Создать комнату, Подключить к комнате одного клиента(юзера)

1. Нажать на Юзера 1 (Клик по юзеру, начать трансляцию)
2. Открыть панель dev tools 
3. Растянуть панель dev tools

Объект ищется элементом inspect

### Окружение

```markdown
- OS: MacOS 12.7.2 (21G1974)
- Версия браузера: 121.0.6167.85 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

Возможно цепочка дефектов с одним источником проблем. Похожие дефекты [Issue 59 ](https://github.com/DmitryTell/Observer/issues/59) [Issue 58 ](https://github.com/DmitryTell/Observer/issues/58) 

<img width="1428" alt="Снимок экрана 2024-02-03 в 18 07 38" src="https://github.com/DmitryTell/Observer/assets/127039439/e0e2087b-db61-414c-a36a-37bfaddfa791">
<img width="1428" alt="Снимок экрана 2024-02-03 в 18 10 59" src="https://github.com/DmitryTell/Observer/assets/127039439/3bae3ceb-7761-42c7-bb49-5315d87fac40">

https://github.com/DmitryTell/Observer/assets/127039439/4351966a-982f-4712-b946-8a64b21b8c5a

**Comment by nikolaykosasha** [comment]
#bug #Major #High

**Comment by DmitryTell** [comment]
Исправил, проверь
![Screenshot_1](https://github.com/DmitryTell/Observer/assets/123256448/06a8f4b2-85a7-4a72-b431-fbccbb58aa19)

**Comment by nikolaykosasha** [comment]
Исправлено. Закрываю.
