### ISSUE TITLE
Сброс набранного текста в окне сообщений при отправки статуса клиентом

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#61]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Серьезность

Значительная ошибка, S3

### Приоритет

Medium

### Фактический результат

Сброс набранного текста в окне сообщений при получении статуса заданий от клиента

### Ожидаемый результат

Набранный текст сохраняется в окне сообщений

### Шаги для воспроизведения

**Предусловия:** Создать комнату. Подключить ученика.

1. Начать трансляцию 
2. Открыть окно сообщений
3. Ввести текст сообщений
4. В плагине нажать кнопку "Help"

### Окружение

```markdown
- Версия плагина: Observer App-1.2.8-test
- Версия браузера: 120.0.6099.234 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

https://github.com/DmitryTell/Observer/assets/127039439/08c9f96d-cbb3-4931-b18b-3f92a6e97fa7

**Comment by nikolaykosasha** [comment]
#bug #Major #Medium

**Comment by DmitryTell** [comment]
Исправил

**Comment by nikolaykosasha** [comment]
Исправлено
