### ISSUE TITLE
[BUG] Данные исчезают из поля заданий после отправки

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#67]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Описание

Данные исчезают из поле ввода заданий после отправки данных

### Серьезность

Значительная ошибка, S3

### Приоритет

Medium

### Фактический результат

Данные исчезаю в поле ввода заданий

### Ожидаемый результат

Данные остаются в поле ввода заданий

### Шаги для воспроизведения

Предусловия: Открыть браузер, Создать комнату.

1. Нажать на кнопку задания
2. Ввести данные в поле ввода задания
3. Нажать кнопку отправить

### Окружение

```markdown
- OS: MacOS 12.7.2 (21G1974)
- Версия браузера: 122.0.6261.69 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

[OB-D67.log](https://github.com/DmitryTell/Observer/files/14639306/OB-D67.log)

https://github.com/DmitryTell/Observer/assets/127039439/f730e5b6-cd8b-4b6e-b1c9-43bc64dbaf90

**Comment by nikolaykosasha** [comment]
@NickMad17 Тебе приходят уведомления?

**Comment by DmitryTell** [comment]
Исправил

**Comment by nikolaykosasha** [comment]
Исправлено. Закрываю.
