### ISSUE TITLE
[BUG] В новой комнате остаются данные заданий из закрытой комнат

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#68]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Серьезность

Минорная ошибка, S4

### Приоритет

Low

### Фактический результат

В поле заданий присутствуют данные из закрытой комнаты

### Ожидаемый результат

В поле заданий отсутствуют данные 

### Шаги для воспроизведения

Предусловия: Открыть браузер, Создать комнату.

1. Нажать на кнопку "Задания"
2. Ввести данные в поле ввода задания
3. Нажать кнопку "Отправить"
4. Нажать кнопку "Выйти"
5. Нажать кнопку "Создать комнату"

### Окружение

```markdown
- OS: MacOS 12.7.2 (21H1015)
- Версия браузера: 122.0.6261.69 (Официальная сборка), (x86_64)
```

### Есть ли что-то еще?

https://github.com/DmitryTell/Observer/assets/127039439/ebd4da21-ff32-41af-b40d-2e700727e7ee

**Comment by DmitryTell** [comment]
Исправил

**Comment by nikolaykosasha** [comment]
Исправлено. Закрываю.
