### ISSUE TITLE
Окно чата остается доступным с несуществующим учеником

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#69]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Описание

В требованиях такого условия нет, думаю это больше к улучшению. Хотя на стороне плагина, чат чистится. 

После дискотека ученика окно чата открыто и хранит информацию о пользователе который вышел из комнаты

### Серьезность

Минорная ошибка, S4

### Приоритет

Low

### Фактический результат

Окно чата открыто со всеми данными

### Ожидаемый результат

Окно чата закрывается и вся информация очищается

### Шаги для воспроизведения

Предусловия: Открыть браузер, Создать комнату, Подключить к комнате клиента(юзера)

1. Нажать на Юзера 1 (Клик по юзеру, начать трансляцию)
2. В окне чата с Юзером 1 ввести данные
3. Отправить данные в чат
4. Нажать "Disconnect" на стороне клиента(плагина)

### Окружение

```markdown
- OS: MacOS 12.7.2 (21G1974)
- Версия браузера: 121.0.6167.85 (Официальная сборка), (x86_64)
- Версия плагина: 1.2.15
```

### Есть ли что-то еще?

https://github.com/DmitryTell/Observer/assets/127039439/87d8b410-d6b0-45b7-aa9c-c7f4a4853840

**Comment by DmitryTell** [comment]
Глеб сказал, оставить так

**Comment by nikolaykosasha** [comment]
Хорошо, закрою Issues
