### ISSUE TITLE
[BUG] Отсутсвует обработчик события удаления папки из проекта

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#73]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Серьезность

Значительная ошибка, S3

### Приоритет

High

### Фактический результат

Папка отображается в дереве проекта и файл в этой папке

### Ожидаемый результат

Папка и файл в ней перестают отображаться в дереве проекта

### Шаги для воспроизведения

Предусловия: Создать подключение с plugin, Начать трансляцию, в проекте создать папку с файлом на стороне плагина

1. Удалить папку с файлом из проекта на стороне плагина

### Окружение

```markdown
- OS: MasOS 12.7.3 (21H1015)
- Plugin: 1.2.15
```

### Есть ли что-то еще?

https://github.com/DmitryTell/Observer/assets/127039439/4c925052-d52b-4131-876e-0c187f9b8f5f

**Comment by kushedow** [comment]
Посмотреть рекурсию дерева и отменить отрисовку папки, которая удалена

**Comment by DmitryTell** [comment]
Исправил. Также теперь если удалить все файлы из папки по одному, то папка отображаться не будет.

**Comment by nikolaykosasha** [comment]
@DmitryTell Не исправил. Если кликнуть по дереву эта папка с файлом снова появляется

**Comment by nikolaykosasha** [comment]
https://github.com/observer-pro/observer_front/assets/127039439/4e8b31df-daa5-45b1-8f0a-c4a3dd5bad34

**Comment by DmitryTell** [comment]
Исправил

**Comment by nikolaykosasha** [comment]
@DmitryTell Подтверждаю. Закрываем
