### ISSUE TITLE
[BUG] Не переключается окно трансляции кода после отправки задания

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#77]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Описание

После отправки заданий невозможно увидеть трансляцию кода окно не переключается. Событие отправляется о начале трансляции.  

### Серьезность

Критическая ошибка, S2

### Приоритет

High

### Фактический результат

Отображается окно отправки заданий

### Ожидаемый результат

Отображается окно трансляции кода

### Шаги для воспроизведения

Предъусловия: Создать комнату. Подключить клиент. 
1. Нажать кнопку задания.
2. Ввести текст в поле задания. 
3. Нажать кнопку "Отправить"
4. Выбрать клиента для трансляции кода" 

### Окружение

```markdown
- OS: Mac OS 12.7.3
- Google Chrome: 123.0.6312.123 (Официальная сборка), (x86_64)
- Plugin:1.2.15
```

**Comment by nikolaykosasha** [comment]
https://github.com/observer-pro/observer_front/assets/127039439/85c8e02b-136b-4353-98aa-cfc1161aa0ef

**Comment by nikolaykosasha** [comment]
Мои предположения, что отсутсвует событие sharing/start, а начинается все с sharing/code_send

**Comment by kushedow** [comment]
Нужен ретест

**Comment by nikolaykosasha** [comment]
Дефект, воспроизводится. @DmitryTell Устрани его пожалуйста.

**Comment by DmitryTell** [comment]
В общем, у меня он воспроизвелся, но немного по-другому.

- Выбираю юзера
- Переключаюсь на задания
- Отправляю задания
- Выбираю юзера и тут... либо не получается переключиться с первого раза, либо юзер открывается, но слетает маркер (что юзер выбран)

Причина: постоянно летящие steps to mentor

**Comment by DmitryTell** [comment]
Вроде исправил. Проверь

**Comment by nikolaykosasha** [comment]
Проблем не наблюдаю. Закрываю Issues.
