### ISSUE TITLE
[BUG] Нет перехода индикации выбранного клиента при трансляции кода

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#78]
### Есть ли уже существующая проблема с этим?

- [X] Я искал(а) существующие проблемы

### Описание

При переключении трансляции между клиентами индикация не переключается между клиентами

### Серьезность

Минорная ошибка, S4

### Приоритет

Medium

### Фактический результат

Индикация выбранного клиента не отображается

### Ожидаемый результат

Индикация отображает выбранного клиента

### Шаги для воспроизведения

Предусловия: Создать комнату. Подключить более 2 клиентов.
1. Начать трансляцию, например клиента Vova
2. Из дерева проекта выбрать файл
3. Начать трансляцию, например у клиента Petya
4. Из дерева проекта выбрать файл
5. Выполнить шаг 1, 3.

### Окружение

```markdown
- OS: Mac OS 12.7.3
- Google Chrome: 123.0.6312.123 (Официальная сборка), (x86_64)
- Plugin:1.2.15
```

### Есть ли что-то еще?

https://github.com/observer-pro/observer_front/assets/127039439/251af43d-9cf7-4943-9bc3-b6b5776cc258

https://github.com/observer-pro/observer_front/assets/127039439/3f2b7fa9-0884-4844-ad0c-30019a7ede81

**Comment by nikolaykosasha** [comment]
Исправление другого дефекта, вызвало исправление этого дефекта. Закрываю.

**Comment by nikolaykosasha** [comment]
Поспешил, все еще актуально

**Comment by DmitryTell** [comment]
Либо он был также по причине постоянно летящих steps to mentor и тогда я его исправил, либо у меня он не воспроизводится

**Comment by nikolaykosasha** [comment]
Дефект воспроизвести не могу. Значит исправлен
