### ISSUE TITLE
[BUG] Геометрическая прогрессия при отправке события sharing/start

### ISSUE THREAD

**Issue by nikolaykosasha** [DmitryTell/Observer#79]
### Есть ли уже существующая проблема с этим?

- [x] Я искал(а) существующие проблемы

### Серьезность

Блокирующая  ошибка, S1

### Приоритет

High

### Окружение

- OS:
- Node:
- npm:

**Comment by DmitryTell** [comment]
Исправлено

**Comment by nikolaykosasha** [comment]
Подтверждаю исправление. Закрываю дефект.

**Comment by nikolaykosasha** [comment]
Расскажешь почему так вела себя система?
